version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/console"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "area:console"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["ci", "dependencies"]
  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "area:web"]
  - package-ecosystem: "docker"
    directory: "/apps/api-python"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "area:api-python"]
  - package-ecosystem: "docker"
    directory: "/apps/api-go"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "area:api-go"]
  - package-ecosystem: "docker"
    directory: "/apps/api-java"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "area:api-java"]

