import type { ApiKeyConfig, LlmProvider, WorkItem } from './types.js';

class OpenSourceLlmProvider implements LlmProvider {
  readonly name = 'open-source-llm';

  async generateFeatureImplementation(input: WorkItem): Promise<string> {
    return `// OSS model generated implementation for ${input.kind} ${input.id}\nexport const feature = ${JSON.stringify(input.title)};`;
  }
}

class ApiKeyBackedProvider implements LlmProvider {
  readonly name: string;

  constructor(private readonly config: Required<Pick<ApiKeyConfig, 'provider' | 'apiKey'>> & ApiKeyConfig) {
    this.name = `${config.provider}-${config.model ?? 'default'}`;
  }

  async generateFeatureImplementation(input: WorkItem): Promise<string> {
    return `// Generated by ${this.name} with key suffix ${this.config.apiKey.slice(-4)}\nexport function implementation(){return ${JSON.stringify(input.body)};}`;
  }
}

/**
 * Chooses between user-owned API-key models and an open-source local fallback.
 */
export function createLlmProvider(config: ApiKeyConfig): LlmProvider {
  if (config.apiKey && config.provider !== 'oss') {
    return new ApiKeyBackedProvider({ ...config, apiKey: config.apiKey });
  }

  return new OpenSourceLlmProvider();
}
