name: Configure Branch Protection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to protect
        default: main
        required: true

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Set protection rules via API
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = core.getInput('branch') || 'main';
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: ['CI', 'Build and Publish Images']
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                require_code_owner_reviews: true
              },
              restrictions: null,
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: true
            });
            core.info(`Branch protection updated for ${branch}.`);

