name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [web, api-python, api-go, api-java]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        if: matrix.app == 'web'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Set up Python
        if: matrix.app == 'api-python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up Go
        if: matrix.app == 'api-go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Set up Java
        if: matrix.app == 'api-java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: |
          make build

