name: Build and Publish Images

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - '.github/workflows/images.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app:
          - web
          - console
          - api-python
          - api-go
          - api-java
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: apps/${{ matrix.app }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ai-${{ matrix.app }}:latest
          platforms: linux/amd64

