name: NPM Audit (Console)

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/console/**'
      - '.github/workflows/npm-audit.yml'
  pull_request:
    paths:
      - 'apps/console/**'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: apps/console
        run: npm ci
      - name: Run npm audit (fail on high)
        working-directory: apps/console
        run: |
          npm audit --audit-level=high --omit=dev

